MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "https://cloudstor.aarnet.edu.au/plus/s/xtixKaxLWmbcyf7/download#mobilenet_v2-ecbe2b5.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "MNV2-FPN-RETINANET"
    FREEZE_CONV_BODY_AT: 0
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  USE_SYNCBN: False
DATASETS:
  TRAIN: ("cityscapes_fine_instanceonly_seg_train_cocostyle",)
  TEST: ("cityscapes_fine_instanceonly_seg_val_cocostyle",)
INPUT:
  MIN_SIZE_TRAIN: (768,)
  MAX_SIZE_TRAIN: 1536
  MIN_SIZE_TEST: 768
  MAX_SIZE_TEST: 1536
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.00125
  WEIGHT_DECAY: 0.0001
  STEPS: (144000,)
  # MAX_ITER: 192000
  # IMS_PER_BATCH: 2
  MAX_ITER: 192000
  IMS_PER_BATCH: 1
  WARMUP_METHOD: "constant"
OUTPUT_DIR: 'cityscapes_experiments/coef_2_1600'